spring:
  profiles:
    include:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
cloud:
  aws:
    region:
      static: ap-northeast-2 #아시아 태평양 (서울)
    stack:
      auto: false
jwt:
  accessTokenExpirationTime:
    int: 30000000